consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Credentials:
    description: Email and password credentials
    example:
      email: magnus@mckenzie.info
      password: htvx6y8d3
    properties:
      email:
        description: Email of user
        example: magnus@mckenzie.info
        format: email
        type: string
      password:
        description: Password of user
        example: htvx6y8d3
        maxLength: 30
        minLength: 6
        type: string
    required:
    - email
    - password
    title: Credentials
    type: object
  EmailPayload:
    description: Email payload
    example:
      email: tiffany_reilly@rosenbaum.biz
    properties:
      email:
        description: Email of user
        example: tiffany_reilly@rosenbaum.biz
        format: email
        type: string
    required:
    - email
    title: EmailPayload
    type: object
  ResetToken:
    description: ResetToken media type (default view)
    example:
      email: Sed provident fugit.
      id: Dignissimos nisi voluptatum.
      token: Mollitia sint.
    properties:
      email:
        description: User email
        example: Sed provident fugit.
        type: string
      id:
        description: User ID
        example: Dignissimos nisi voluptatum.
        type: string
      token:
        description: New token
        example: Mollitia sint.
        type: string
    required:
    - id
    - email
    - token
    title: 'Mediatype identifier: resettokenmedia; view=default'
    type: object
  UserPayload:
    description: UserPayload
    example:
      active: true
      email: ollie.hilll@smith.info
      externalId: Doloremque aut sed ut impedit voluptatum debitis.
      namespaces:
      - Placeat reprehenderit similique quo.
      - Placeat reprehenderit similique quo.
      organizations:
      - Occaecati ut excepturi et deleniti quis.
      - Occaecati ut excepturi et deleniti quis.
      password: 3v789xuu49
      roles:
      - Officiis velit quaerat nam velit incidunt.
      - Officiis velit quaerat nam velit incidunt.
      - Officiis velit quaerat nam velit incidunt.
      token: Voluptatem reprehenderit quisquam maxime nam non.
    properties:
      active:
        default: false
        description: Status of user account
        example: true
        type: boolean
      email:
        description: Email of user
        example: ollie.hilll@smith.info
        format: email
        type: string
      externalId:
        description: External id of user
        example: Doloremque aut sed ut impedit voluptatum debitis.
        type: string
      namespaces:
        description: List of namespaces this user belongs to
        example:
        - Placeat reprehenderit similique quo.
        - Placeat reprehenderit similique quo.
        items:
          example: Placeat reprehenderit similique quo.
          type: string
        type: array
      organizations:
        description: List of organizations to which this user belongs to
        example:
        - Occaecati ut excepturi et deleniti quis.
        - Occaecati ut excepturi et deleniti quis.
        items:
          example: Occaecati ut excepturi et deleniti quis.
          type: string
        type: array
      password:
        description: Password of user
        example: 3v789xuu49
        maxLength: 30
        minLength: 6
        type: string
      roles:
        description: Roles of user
        example:
        - Officiis velit quaerat nam velit incidunt.
        - Officiis velit quaerat nam velit incidunt.
        - Officiis velit quaerat nam velit incidunt.
        items:
          example: Officiis velit quaerat nam velit incidunt.
          type: string
        type: array
      token:
        description: Token for email verification
        example: Voluptatem reprehenderit quisquam maxime nam non.
        type: string
    required:
    - email
    title: UserPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
  users:
    description: users media type (default view)
    example:
      active: true
      email: thad@herman.name
      externalId: Possimus ullam occaecati quae.
      id: Rerum aliquid in sit reprehenderit ea.
      namespaces:
      - Placeat reprehenderit similique quo.
      - Placeat reprehenderit similique quo.
      - Placeat reprehenderit similique quo.
      organizations:
      - Occaecati ut excepturi et deleniti quis.
      - Occaecati ut excepturi et deleniti quis.
      - Occaecati ut excepturi et deleniti quis.
      roles:
      - Officiis velit quaerat nam velit incidunt.
      - Officiis velit quaerat nam velit incidunt.
    properties:
      active:
        default: false
        description: Status of user account
        example: true
        type: boolean
      email:
        description: Email of user
        example: thad@herman.name
        format: email
        type: string
      externalId:
        description: External id of user
        example: Possimus ullam occaecati quae.
        type: string
      id:
        description: Unique user ID
        example: Rerum aliquid in sit reprehenderit ea.
        type: string
      namespaces:
        description: List of namespaces this user belongs to
        example:
        - Placeat reprehenderit similique quo.
        - Placeat reprehenderit similique quo.
        - Placeat reprehenderit similique quo.
        items:
          example: Placeat reprehenderit similique quo.
          type: string
        type: array
      organizations:
        description: List of organizations to which this user belongs to
        example:
        - Occaecati ut excepturi et deleniti quis.
        - Occaecati ut excepturi et deleniti quis.
        - Occaecati ut excepturi et deleniti quis.
        items:
          example: Occaecati ut excepturi et deleniti quis.
          type: string
        type: array
      roles:
        description: Roles of user
        example:
        - Officiis velit quaerat nam velit incidunt.
        - Officiis velit quaerat nam velit incidunt.
        items:
          example: Officiis velit quaerat nam velit incidunt.
          type: string
        type: array
    required:
    - id
    - email
    - roles
    - externalId
    - active
    title: 'Mediatype identifier: application/vnd.goa.user+json; view=default'
    type: object
host: localhost:8080
info:
  description: A service that provides basic access to the user data
  title: The user microservice
  version: "1.0"
paths:
  /swagger-ui/{filepath}:
    get:
      operationId: swagger#/swagger-ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download swagger-ui/dist
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
  /users:
    post:
      description: Creates user
      operationId: user#create
      parameters:
      - description: UserPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create user
      tags:
      - user
  /users/{userId}:
    get:
      description: Get user by id
      operationId: user#get
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: get user
      tags:
      - user
    put:
      description: Update user
      operationId: user#update
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: UserPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: update user
      tags:
      - user
  /users/find:
    post:
      description: Find a user by email+password
      operationId: user#find
      parameters:
      - description: Email and password credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/Credentials'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: find user
      tags:
      - user
  /users/find/email:
    post:
      description: Find a user by email
      operationId: user#findByEmail
      parameters:
      - description: Email payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/EmailPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: findByEmail user
      tags:
      - user
  /users/me:
    get:
      description: Retrieves the user information for the authenticated user
      operationId: user#getMe
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: getMe user
      tags:
      - user
  /users/verification/reset:
    post:
      description: Reset verification token
      operationId: user#resetVerificationToken
      parameters:
      - description: Email payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/EmailPayload'
      produces:
      - application/vnd.goa.error
      - resettokenmedia
      responses:
        "200":
          description: Verification token reset
          schema:
            $ref: '#/definitions/ResetToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: resetVerificationToken user
      tags:
      - user
  /users/verify:
    get:
      description: Verify a user by token
      operationId: user#verify
      parameters:
      - description: Token
        in: query
        name: token
        required: false
        type: string
      produces:
      - application/vnd.goa.error
      - plain/text
      responses:
        "200":
          description: User is verified
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: verify user
      tags:
      - user
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/users'
schemes:
- http
swagger: "2.0"
