consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Credentials:
    description: Username and password credentials
    example:
      password: 0arnperc
      username: wFhMfno
    properties:
      password:
        description: Password of user
        example: 0arnperc
        maxLength: 30
        minLength: 6
        type: string
      username:
        description: Name of user
        example: wFhMfno
        pattern: ^([a-zA-Z0-9@]{4,30})$
        type: string
    required:
    - username
    - password
    title: Credentials
    type: object
  UserPayload:
    description: UserPayload
    example:
      active: true
      email: brigitte_koepp@ferry.net
      externalId: Veritatis veniam sed voluptatibus.
      password: x75md877qp
      roles:
      - Placeat reprehenderit similique quo.
      - Placeat reprehenderit similique quo.
      - Placeat reprehenderit similique quo.
      username: ApPq
    properties:
      active:
        default: false
        description: Status of user account
        example: true
        type: boolean
      email:
        description: Email of user
        example: brigitte_koepp@ferry.net
        format: email
        type: string
      externalId:
        description: External id of user
        example: Veritatis veniam sed voluptatibus.
        type: string
      password:
        description: Password of user
        example: x75md877qp
        maxLength: 30
        minLength: 6
        type: string
      roles:
        description: Roles of user
        example:
        - Placeat reprehenderit similique quo.
        - Placeat reprehenderit similique quo.
        - Placeat reprehenderit similique quo.
        items:
          example: Placeat reprehenderit similique quo.
          type: string
        type: array
      username:
        description: Name of user
        example: ApPq
        pattern: ^([a-zA-Z0-9@]{4,30})$
        type: string
    required:
    - username
    - email
    - password
    - roles
    - externalId
    title: UserPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
  users:
    description: users media type (default view)
    example:
      active: true
      email: thad@herman.name
      externalId: Possimus ullam occaecati quae.
      id: Rerum aliquid in sit reprehenderit ea.
      roles:
      - Placeat reprehenderit similique quo.
      - Placeat reprehenderit similique quo.
      - Placeat reprehenderit similique quo.
      username: dkPRrKW
    properties:
      active:
        default: false
        description: Status of user account
        example: true
        type: boolean
      email:
        description: Email of user
        example: thad@herman.name
        format: email
        type: string
      externalId:
        description: External id of user
        example: Possimus ullam occaecati quae.
        type: string
      id:
        description: Unique user ID
        example: Rerum aliquid in sit reprehenderit ea.
        type: string
      roles:
        description: Roles of user
        example:
        - Placeat reprehenderit similique quo.
        - Placeat reprehenderit similique quo.
        - Placeat reprehenderit similique quo.
        items:
          example: Placeat reprehenderit similique quo.
          type: string
        type: array
      username:
        description: Name of user
        example: dkPRrKW
        pattern: ^([a-zA-Z0-9@]{4,30})$
        type: string
    required:
    - id
    - username
    - email
    - roles
    - externalId
    - active
    title: 'Mediatype identifier: application/vnd.goa.user+json; view=default'
    type: object
host: localhost:8080
info:
  description: A service that provides basic access to the user data
  title: The user microservice
  version: "1.0"
paths:
  /swagger-ui/{filepath}:
    get:
      operationId: swagger#/swagger-ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download swagger-ui/dist
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
  /users/:
    post:
      description: Creates user
      operationId: user#create
      parameters:
      - description: UserPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserPayload'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: create user
      tags:
      - user
  /users/{userId}:
    get:
      description: Get user by id
      operationId: user#get
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: get user
      tags:
      - user
    put:
      description: Update user
      operationId: user#update
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: UserPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserPayload'
      produces:
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "404":
          description: Not Found
      schemes:
      - http
      summary: update user
      tags:
      - user
  /users/find:
    post:
      description: Find a user by username+password
      operationId: user#find
      parameters:
      - description: Username and password credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/Credentials'
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: find user
      tags:
      - user
  /users/me:
    get:
      description: Retrieves the user information for the authenticated user
      operationId: user#getMe
      parameters:
      - description: User ID
        in: query
        name: userId
        required: false
        type: string
      produces:
      - application/vnd.goa.error
      - application/vnd.goa.user+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: getMe user
      tags:
      - user
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/users'
schemes:
- http
swagger: "2.0"
